//Model
model = {
    cardsOnHand: [],
    cardsOnTable: [],
    deckOfCards: [
        {
            id: 1,
            type: "Hearts",
            value: "Ace",
            img: "./img/hearts.png",
        },
        {
            id: 2,
            type: "Hearts",
            value: "2",
            img: "./img/hearts.png",
        },
        {
            id: 3,
            type: "Hearts",
            value: "3",
            img: "./img/hearts.png",
        },
        {
            id: 4,
            type: "Hearts",
            value: "4",
            img: "./img/hearts.png",
        },
        {
            id: 5,
            type: "Hearts",
            value: "5",
            img: "./img/hearts.png",
        },
        {
            id: 6,
            type: "Hearts",
            value: "6",
            img: "./img/hearts.png",
        },
        {
            id: 7,
            type: "Hearts",
            value: "7",
            img: "./img/hearts.png",
        },
        {
            id: 8,
            type: "Hearts",
            value: "8",
            img: "./img/hearts.png",
        },
        {
            id: 9,
            type: "Hearts",
            value: "9",
            img: "./img/hearts.png",
        },
        {
            id: 10,
            type: "Hearts",
            value: "10",
            img: "./img/hearts.png",
        },
        {
            id: 11,
            type: "Hearts",
            value: "Jack",
            img: "./img/hearts.png",
        },
        {
            id: 12,
            type: "Hearts",
            value: "Queen",
            img: "./img/hearts.png",
        },
        {
            id: 13,
            type: "Hearts",
            value: "King",
            img: "./img/hearts.png",
        },
        {
            id: 14,
            type: "Spades",
            value: "Ace",
            img: "./img/spades.png",
        },
        {
            id: 15,
            type: "Spades",
            value: "2",
            img: "./img/spades.png",
        },
        {
            id: 16,
            type: "Spades",
            value: "3",
            img: "./img/spades.png",
        },
        {
            id: 17,
            type: "Spades",
            value: "4",
            img: "./img/spades.png",
        },
        {
            id: 18,
            type: "Spades",
            value: "5",
            img: "./img/spades.png",
        },
        {
            id: 19,
            type: "Spades",
            value: "6",
            img: "./img/spades.png",
        },
        {
            id: 20,
            type: "Spades",
            value: "7",
            img: "./img/spades.png",
        },
        {
            id: 21,
            type: "Spades",
            value: "8",
            img: "./img/spades.png",
        },
        {
            id: 22,
            type: "Spades",
            value: "9",
            img: "./img/spades.png",
        },
        {
            id: 23,
            type: "Spades",
            value: "10",
            img: "./img/spades.png",
        },
        {
            id: 24,
            type: "Spades",
            value: "Jack",
            img: "./img/spades.png",
        },
        {
            id: 25,
            type: "Spades",
            value: "Queen",
            img: "./img/spades.png",
        },
        {
            id: 26,
            type: "Spades",
            value: "King",
            img: "./img/spades.png",
        },
        {
            id: 27,
            type: "Diamonds",
            value: "Ace",
            img: "./img/diamonds.png",
        },
        {
            id: 28,
            type: "Diamonds",
            value: "2",
            img: "./img/diamonds.png",
        },
        {
            id: 29,
            type: "Diamonds",
            value: "3",
            img: "./img/diamonds.png",
        },
        {
            id: 30,
            type: "Diamonds",
            value: "4",
            img: "./img/diamonds.png",
        },
        {
            id: 31,
            type: "Diamonds",
            value: "5",
            img: "./img/diamonds.png",
        },
        {
            id: 32,
            type: "Diamonds",
            value: "6",
            img: "./img/diamonds.png",
        },
        {
            id: 33,
            type: "Diamonds",
            value: "7",
            img: "./img/diamonds.png",
        },
        {
            id: 34,
            type: "Diamonds",
            value: "8",
            img: "./img/diamonds.png",
        },
        {
            id: 35,
            type: "Diamonds",
            value: "9",
            img: "./img/diamonds.png",
        },
        {
            id: 36,
            type: "Diamonds",
            value: "10",
            img: "./img/diamonds.png",
        },
        {
            id: 37,
            type: "Diamonds",
            value: "Jack",
            img: "./img/diamonds.png",
        },
        {
            id: 38,
            type: "Diamonds",
            value: "Queen",
            img: "./img/diamonds.png",
        },
        {
            id: 39,
            type: "Diamonds",
            value: "King",
            img: "./img/diamonds.png",
        },
        {
            id: 40,
            type: "Clubs",
            value: "Ace",
            img: "./img/clubs.png",
        },
        {
            id: 41,
            type: "Clubs",
            value: "2",
            img: "./img/clubs.png",
        },
        {
            id: 42,
            type: "Clubs",
            value: "3",
            img: "./img/clubs.png",
        },
        {
            id: 43,
            type: "Clubs",
            value: "4",
            img: "./img/clubs.png",
        },
        {
            id: 44,
            type: "Clubs",
            value: "5",
            img: "./img/clubs.png",
        },
        {
            id: 45,
            type: "Clubs",
            value: "6",
            img: "./img/clubs.png",
        },
        {
            id: 46,
            type: "Clubs",
            value: "7",
            img: "./img/clubs.png",
        },
        {
            id: 47,
            type: "Clubs",
            value: "8",
            img: "./img/clubs.png",
        },
        {
            id: 48,
            type: "Clubs",
            value: "9",
            img: "./img/clubs.png",
        },
        {
            id: 49,
            type: "Clubs",
            value: "10",
            img: "./img/clubs.png",
        },
        {
            id: 50,
            type: "Clubs",
            value: "Jack",
            img: "./img/clubs.png",
        },
        {
            id: 51,
            type: "Clubs",
            value: "Queen",
            img: "./img/clubs.png",
        },
        {
            id: 52,
            type: "Clubs",
            value: "King",
            img: "./img/clubs.png",
        },
    ]
};